/**
 * Connector Template — Interface for all corpus data connectors.
 *
 * Each connector fetches data from an external source, normalizes it
 * into CorpusArticle format, and supports dry-run validation.
 *
 * Connectors are generated by Claude Code workflows and registered
 * in connectors/registry.json after validation.
 */

import type { CorpusArticle } from "../lib/db/corpus";

/** Raw record from an external source before normalization. */
export interface RawRecord {
  [key: string]: unknown;
}

/** Result of a connector validation run. */
export interface ValidationResult {
  ok: boolean;
  sampleCount: number;
  errors: string[];
  samples?: CorpusArticle[];
}

/** Interface that every connector must implement. */
export interface CorpusConnector {
  /** Unique connector ID (matches registry.json). */
  id: string;

  /** Human-readable name. */
  name: string;

  /** Target domain (e.g. "legal", "fiscal"). */
  domain: string;

  /** URL of the data source. */
  sourceUrl: string;

  /**
   * Fetch raw records from the external source.
   * @param opts.limit - Max records to fetch (for dry-run).
   */
  fetch(opts?: { limit?: number }): Promise<RawRecord[]>;

  /**
   * Normalize raw records into CorpusArticle format.
   * Applies field mapping, hierarchy, institutes, keywords.
   */
  normalize(records: RawRecord[]): CorpusArticle[];

  /**
   * Dry-run validation: fetch a small sample, normalize, verify format.
   * Returns ok=true if the connector produces valid articles.
   */
  validate(): Promise<ValidationResult>;
}

/**
 * Helper to create a connector with defaults.
 * Use this in generated connectors:
 *
 * ```ts
 * import { defineConnector } from "./template";
 * export default defineConnector({ id: "...", ... });
 * ```
 */
export function defineConnector(
  connector: CorpusConnector
): CorpusConnector {
  return connector;
}
