/**
 * Target Schemas — Schema destinazione per ogni DataType.
 *
 * Definisce i campi target normalizzati per ciascun tipo di dato business.
 * Usato dal MappingEngine e dal mapper pipeline per sapere quali colonne
 * sono disponibili nella tabella destinazione.
 *
 * ADR: adr-ai-mapping-hybrid.md
 */

/**
 * Schema target per tipo di dato.
 * Chiave = DataType semplificato (es. "invoices", "contacts").
 * Valore = lista ordinata di nomi colonne normalizzati.
 */
export const TARGET_SCHEMAS: Record<string, string[]> = {
  invoices: [
    "invoice_number",
    "invoice_date",
    "due_date",
    "net_amount",
    "vat_amount",
    "gross_amount",
    "vat_rate",
    "currency",
    "company_name",
    "vat_number",
    "tax_code",
    "description",
    "status",
    "payment_status",
  ],
  contacts: [
    "first_name",
    "last_name",
    "email",
    "phone",
    "company_name",
    "job_title",
    "address",
    "city",
    "country",
    "notes",
    "created_at",
    "updated_at",
  ],
  documents: [
    "file_name",
    "file_type",
    "file_size",
    "url",
    "folder_path",
    "created_at",
    "modified_at",
    "owner",
    "shared_with",
  ],
  tickets: [
    "ticket_id",
    "subject",
    "description",
    "status",
    "priority",
    "assignee",
    "reporter",
    "created_at",
    "updated_at",
    "resolved_at",
  ],
  deals: [
    "deal_name",
    "amount",
    "currency",
    "stage",
    "pipeline",
    "close_date",
    "probability",
    "owner",
    "company_name",
    "description",
    "created_at",
    "updated_at",
  ],
  companies: [
    "company_name",
    "industry",
    "website",
    "phone",
    "email",
    "address",
    "city",
    "country",
    "postal_code",
    "province",
    "vat_number",
    "tax_id",
    "employee_count",
    "annual_revenue",
    "description",
    "created_at",
    "updated_at",
  ],
  payments: [
    "payment_id",
    "amount",
    "currency",
    "status",
    "payment_method",
    "customer_id",
    "customer_email",
    "description",
    "created_at",
  ],
  subscriptions: [
    "subscription_id",
    "customer_id",
    "status",
    "amount",
    "currency",
    "billing_interval",
    "start_date",
    "end_date",
    "created_at",
    "updated_at",
  ],
  products: [
    "product_id",
    "name",
    "description",
    "sku",
    "unit_price",
    "currency",
    "category",
    "tax_rate",
    "unit_of_measure",
    "is_active",
    "created_at",
    "updated_at",
  ],
  quotes: [
    "quote_id",
    "quote_number",
    "title",
    "status",
    "net_amount",
    "vat_amount",
    "gross_amount",
    "currency",
    "issue_date",
    "expiry_date",
    "company_name",
    "contact_name",
    "description",
    "created_at",
    "updated_at",
  ],
  orders: [
    "order_id",
    "order_number",
    "status",
    "net_amount",
    "vat_amount",
    "gross_amount",
    "currency",
    "order_date",
    "delivery_date",
    "company_name",
    "shipping_address",
    "description",
    "created_at",
    "updated_at",
  ],
  leads: [
    "lead_id",
    "first_name",
    "last_name",
    "email",
    "phone",
    "company_name",
    "job_title",
    "lead_source",
    "status",
    "rating",
    "industry",
    "description",
    "created_at",
    "updated_at",
  ],
  opportunities: [
    "opportunity_id",
    "name",
    "amount",
    "currency",
    "stage",
    "probability",
    "close_date",
    "account_name",
    "owner",
    "type",
    "lead_source",
    "description",
    "created_at",
    "updated_at",
  ],
  events: [
    "event_id",
    "subject",
    "description",
    "start_date",
    "end_date",
    "location",
    "organizer",
    "attendees",
    "is_all_day",
    "status",
    "created_at",
    "updated_at",
  ],
  campaigns: [
    "campaign_id",
    "name",
    "type",
    "status",
    "start_date",
    "end_date",
    "budget",
    "actual_cost",
    "expected_revenue",
    "num_sent",
    "num_responses",
    "description",
    "created_at",
    "updated_at",
  ],
  contracts: [
    "contract_id",
    "contract_number",
    "account_name",
    "status",
    "start_date",
    "end_date",
    "contract_term",
    "owner",
    "description",
    "created_at",
    "updated_at",
  ],
  refunds: [
    "refund_id",
    "amount",
    "currency",
    "status",
    "reason",
    "payment_id",
    "customer_id",
    "customer_email",
    "description",
    "created_at",
  ],
  disputes: [
    "dispute_id",
    "amount",
    "currency",
    "status",
    "reason",
    "payment_id",
    "customer_id",
    "evidence_due_date",
    "created_at",
    "updated_at",
  ],
  suppliers: [
    "supplier_id",
    "company_name",
    "vat_number",
    "tax_code",
    "email",
    "phone",
    "address",
    "city",
    "province",
    "postal_code",
    "country",
    "payment_terms",
    "created_at",
    "updated_at",
  ],
};

/**
 * Ritorna lo schema target per un DataType.
 * Se il tipo non esiste, ritorna un array vuoto.
 */
export function getTargetSchema(dataType: string): string[] {
  return TARGET_SCHEMAS[dataType] ?? [];
}

/**
 * Ritorna tutti i DataType con schema target definito.
 */
export function getAvailableDataTypes(): string[] {
  return Object.keys(TARGET_SCHEMAS);
}
